package block

var (
	ST_BIGINT                   string = "bigint"
	ST_INTEGER                  string = "integer"
	ST_SMALLINT                 string = "smallint"
	ST_TINYINT                  string = "tinyint"
	ST_BOOLEAN                  string = "boolean"
	ST_DATE                     string = "date"
	ST_DECIMAL                  string = "decimal"
	ST_REAL                     string = "real"
	ST_DOUBLE                   string = "double"
	ST_HYPER_LOG_LOG            string = "HyperLogLog"
	ST_QDIGEST                  string = "qdigest"
	ST_TDIGEST                  string = "tdigest"
	ST_P4_HYPER_LOG_LOG         string = "P4HyperLogLog"
	ST_INTERVAL_DAY_TO_SECOND   string = "interval day to second"
	ST_INTERVAL_YEAR_TO_MONTH   string = "interval year to month"
	ST_TIMESTAMP                string = "timestamp"
	ST_TIMESTAMP_WITH_TIME_ZONE string = "timestamp with time zone"
	ST_TIME                     string = "time"
	ST_TIME_WITH_TIME_ZONE      string = "time with time zone"
	ST_VARBINARY                string = "varbinary"
	ST_VARCHAR                  string = "varchar"
	ST_CHAR                     string = "char"
	ST_ROW                      string = "row"
	ST_ARRAY                    string = "array"
	ST_MAP                      string = "map"
	ST_JSON                     string = "json"
	ST_IPADDRESS                string = "ipaddress"
	ST_GEOMETRY                 string = "Geometry"
	ST_UUID                     string = "uuid"
)
